name: Build Docs
on:
  push:
    branches:
      - trunk
    paths:
      - 'generation/**'
      - 'data/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm ci
        working-directory: generation
      - run: npm run generate
        working-directory: generation
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automatically build docs
